// Generated by Wrangler by running `wrangler types`

interface Env {
	APPLICATION_ID: string;
	PUBLIC_KEY: string;
	BOT_TOKEN: string;
	OKAZURI_API_URL: string;
	ERROR_LOG_WEBHOOK: string;
	DB: D1Database;
}
