name = "okazuri-bot"
main = "src/index.ts"
compatibility_date = "2024-01-12"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
APPLICATION_ID = "1279716906688839711"
PUBLIC_KEY = "afab84e384302cf3e563efd194f96d13b15613f26926bad395ce601bc68e54f2"
BOT_TOKEN = "MTI3OTcxNjkwNjY4ODgzOTcxMQ.GrDfh-.IqZp_wbV8bfn0ojRGZE8yLOdeAQfeykioIjztQ"
HERMES_API_URL = "https://hermes-api.nae.quest/api"
ERROR_LOG_WEBHOOK = "https://discord.com/api/webhooks/1279738358297530388/lIzz9DUOb1LtEeG28SOOAxeIwJnWHUJxTHrFn_KrHhcmLHKk4LsGlhwK4C8j0rqrGlKN"
